BEGIN TRANSACTION;
CREATE TABLE clanovi (
    id TEXT PRIMARY KEY,
    ime TEXT NOT NULL,
    prezime TEXT DEFAULT 'Zehić',
    spol TEXT NOT NULL, -- 'M' ili 'Ž'
    generacija INTEGER NOT NULL,
    grana TEXT NOT NULL,
    datumi TEXT,
    napomene TEXT,
    roditelj_id TEXT,
    ime_roditelja TEXT,
    supruznik_ime TEXT,
    supruznik_napomene TEXT,
    je_supruznik INTEGER DEFAULT 0
);
INSERT INTO "clanovi" VALUES('sp_ibrahim_0','Hanča','','Ž',1,'Korijen','','Supruga','ibrahim_0','Ibrahim','Ibrahim','',1);
INSERT INTO "clanovi" VALUES('ibrahim_0','Ibrahim','Zehić','M',1,'Korijen','','',NULL,NULL,'Hanča','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_adem_1','Mejra','','Ž',2,'Grana Adem','','Supruga','adem_1','Adem','Adem','',1);
INSERT INTO "clanovi" VALUES('adem_1','Adem','Zehić','M',2,'Grana Adem','1855 – 1938','','ibrahim_root','Ibrahim','Mejra','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_avdo_adem','Azemina','','Ž',3,'Grana Adem','','r. Husejnović','avdo_adem','Avdo','Avdo','',1);
INSERT INTO "clanovi" VALUES('avdo_adem','Avdo','Zehić','M',3,'Grana Adem','1887 – 1957','','adem_1','Adem','Azemina','r. Husejnović',0);
INSERT INTO "clanovi" VALUES('osman_avdo_adem','Osman','Zehić','M',4,'Grana Adem','','n. Poginuo','avdo_adem','Avdo','','',0);
INSERT INTO "clanovi" VALUES('nurija_avdo_adem','Nurija','Zehić','M',4,'Grana Adem','','n. Poginuo','avdo_adem','Avdo','','',0);
INSERT INTO "clanovi" VALUES('hatidza_avdo_adem','Hatidza','Zehić','Ž',4,'Grana Adem','','','avdo_adem','Avdo','','',0);
INSERT INTO "clanovi" VALUES('sp_beriz_avdo_adem','Nura','','Ž',4,'Grana Adem','','Supruga','beriz_avdo_adem','Beriz','Beriz','',1);
INSERT INTO "clanovi" VALUES('beriz_avdo_adem','Beriz','Zehić','M',4,'Grana Adem','','','avdo_adem','Avdo','Nura','Supruga',0);
INSERT INTO "clanovi" VALUES('seida_beriz','Seida','Zehić','Ž',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('bahrija_beriz','Bahrija','Zehić','Ž',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('hatidza_beriz','Hatidža','Zehić','Ž',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('zemina_beriz','Zemina','Zehić','Ž',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('dzevad_beriz','Dževad','Zehić','M',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('beriz_dzevad','Beriz','Zehić','M',6,'Grana Adem','','','dzevad_beriz','Dževad','','',0);
INSERT INTO "clanovi" VALUES('nedzad_dzevad','Nedžad','Zehić','M',6,'Grana Adem','','','dzevad_beriz','Dževad','','',0);
INSERT INTO "clanovi" VALUES('halida_beriz','Halida','Zehić','Ž',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('nesad_beriz','Nešad','Zehić','M',5,'Grana Adem','','','beriz_avdo_adem','Beriz','','',0);
INSERT INTO "clanovi" VALUES('azra_nesad','Azra','Zehić','Ž',6,'Grana Adem','','','nesad_beriz','Nešad','','',0);
INSERT INTO "clanovi" VALUES('almedina_nesad','Almedina','Zehić','Ž',6,'Grana Adem','','','nesad_beriz','Nešad','','',0);
INSERT INTO "clanovi" VALUES('kenan_nesad','Kenan','Zehić','M',6,'Grana Adem','','','nesad_beriz','Nešad','','',0);
INSERT INTO "clanovi" VALUES('dzenan_nesad','Dženan','Zehić','M',6,'Grana Adem','','','nesad_beriz','Nešad','','',0);
INSERT INTO "clanovi" VALUES('sp_mujo_adem','Šemsa','','Ž',3,'Grana Adem','','r. Husejnovca','mujo_adem','Mujo','Mujo','',1);
INSERT INTO "clanovi" VALUES('mujo_adem','Mujo','Zehić','M',3,'Grana Adem','1897 – 1934','','adem_1','Adem','Šemsa','r. Husejnovca',0);
INSERT INTO "clanovi" VALUES('sp_husnija_mujo','Sajda','','Ž',4,'Grana Adem','1926 – 1999','r. Čilašević','husnija_mujo','Husnija','Husnija','',1);
INSERT INTO "clanovi" VALUES('husnija_mujo','Husnija','Zehić','M',4,'Grana Adem','1925 – 1988','','mujo_adem','Mujo','Sajda','r. Čilašević',0);
INSERT INTO "clanovi" VALUES('sp_fahrudin_husnija','Mulfeta','','Ž',5,'Grana Adem','','r. Hodžić (Sniježnica)','fahrudin_husnija','Fahrudin','Fahrudin','',1);
INSERT INTO "clanovi" VALUES('fahrudin_husnija','Fahrudin','Zehić','M',5,'Grana Adem','','','husnija_mujo','Husnija','Mulfeta','r. Hodžić (Sniježnica)',0);
INSERT INTO "clanovi" VALUES('sp_zaim_fahrudin','Samra','','Ž',6,'Grana Adem','','r. Ramić (Glinje)','zaim_fahrudin','Zaim','Zaim','',1);
INSERT INTO "clanovi" VALUES('zaim_fahrudin','Zaim','Zehić','M',6,'Grana Adem','','','fahrudin_husnija','Fahrudin','Samra','r. Ramić (Glinje)',0);
INSERT INTO "clanovi" VALUES('armin_zaim','Armin','Zehić','M',7,'Grana Adem','','','zaim_fahrudin','Zaim','','',0);
INSERT INTO "clanovi" VALUES('emina_fahrudin','Emina','Zehić','Ž',6,'Grana Adem','','','fahrudin_husnija','Fahrudin','','',0);
INSERT INTO "clanovi" VALUES('sp_vahidin_fahrudin','Nedžmira','','Ž',6,'Grana Adem','','r. Bilalić (T. Brdo)','vahidin_fahrudin','Vahidin','Vahidin','',1);
INSERT INTO "clanovi" VALUES('vahidin_fahrudin','Vahidin','Zehić','M',6,'Grana Adem','','','fahrudin_husnija','Fahrudin','Nedžmira','r. Bilalić (T. Brdo)',0);
INSERT INTO "clanovi" VALUES('esma_vahidin','Esma','Zehić','Ž',7,'Grana Adem','','','vahidin_fahrudin','Vahidin','','',0);
INSERT INTO "clanovi" VALUES('sajda_vahidin','Sajda','Zehić','Ž',7,'Grana Adem','','','vahidin_fahrudin','Vahidin','','',0);
INSERT INTO "clanovi" VALUES('sp_adnan_fahrudin','Mirela','','Ž',6,'Grana Adem','','r. Mujić (T. Brdo)','adnan_fahrudin','Adnan','Adnan','',1);
INSERT INTO "clanovi" VALUES('adnan_fahrudin','Adnan','Zehić','M',6,'Grana Adem','','','fahrudin_husnija','Fahrudin','Mirela','r. Mujić (T. Brdo)',0);
INSERT INTO "clanovi" VALUES('adel_adnan','Adel','Zehić','M',7,'Grana Adem','','','adnan_fahrudin','Adnan','','',0);
INSERT INTO "clanovi" VALUES('meliha_adnan','Meliha','Zehić','Ž',7,'Grana Adem','','','adnan_fahrudin','Adnan','','',0);
INSERT INTO "clanovi" VALUES('vedad_adnan','Vedad','Zehić','M',7,'Grana Adem','','','adnan_fahrudin','Adnan','','',0);
INSERT INTO "clanovi" VALUES('semsa_husnija','Šemsa','Zehić','Ž',5,'Grana Adem','','u. Bilalić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('zurijeta_husnija','Zurijeta','Zehić','Ž',5,'Grana Adem','','u. Hadžić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('nura_husnija','Nura','Zehić','Ž',5,'Grana Adem','','u. Aljić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('mensura_husnija','Mensura','Zehić','Ž',5,'Grana Adem','','u. Omerović','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('izeta_husnija','Izeta','Zehić','Ž',5,'Grana Adem','','u. Murtić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('hatidza_husnija','Hatidža','Zehić','Ž',5,'Grana Adem','','u. Redžić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('fatima_husnija','Fatima','Zehić','Ž',5,'Grana Adem','','u. Alić','husnija_mujo','Husnija','','',0);
INSERT INTO "clanovi" VALUES('sp_kadraga_husnija','Zekira','','Ž',5,'Grana Adem','','r. Janja','kadraga_husnija','Kadraga','Kadraga','',1);
INSERT INTO "clanovi" VALUES('kadraga_husnija','Kadraga','Zehić','M',5,'Grana Adem','','','husnija_mujo','Husnija','Zekira','r. Janja',0);
INSERT INTO "clanovi" VALUES('sp_azra_kadraga','Mirza Halilović','','M',6,'Grana Adem','','Suprug','azra_kadraga','Azra','Azra','r. Zehić',1);
INSERT INTO "clanovi" VALUES('azra_kadraga','Azra','Zehić','Ž',6,'Grana Adem','','r. Zehić','kadraga_husnija','Kadraga','Mirza Halilović','Suprug',0);
INSERT INTO "clanovi" VALUES('hamza_mirza','Hamza','Zehić','M',7,'Grana Adem','','','azra_kadraga','Azra','','',0);
INSERT INTO "clanovi" VALUES('sp_samir_kadraga','Merima','','Ž',6,'Grana Adem','','Supruga','samir_kadraga','Samir','Samir','',1);
INSERT INTO "clanovi" VALUES('samir_kadraga','Samir','Zehić','M',6,'Grana Adem','','','kadraga_husnija','Kadraga','Merima','Supruga',0);
INSERT INTO "clanovi" VALUES('adna_samir','Adna','Zehić','Ž',7,'Grana Adem','','','samir_kadraga','Samir','','',0);
INSERT INTO "clanovi" VALUES('sp_hadzaga_mujo','Zarfa','','Ž',4,'Grana Adem','','r. T. Brdo','hadzaga_mujo','Hadžaga','Hadžaga','',1);
INSERT INTO "clanovi" VALUES('hadzaga_mujo','Hadžaga','Zehić','M',4,'Grana Adem','','','mujo_adem','Mujo','Zarfa','r. T. Brdo',0);
INSERT INTO "clanovi" VALUES('sadik_hadzaga','Sadik','Zehić','M',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('meliha_sadik','Meliha','Zehić','Ž',6,'Grana Adem','','','sadik_hadzaga','Sadik','','',0);
INSERT INTO "clanovi" VALUES('hido_sadik','Hido','Zehić','M',6,'Grana Adem','','','sadik_hadzaga','Sadik','','',0);
INSERT INTO "clanovi" VALUES('zlatka_hadzaga','Zlatka','Zehić','Ž',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('sadika_hadzaga','Sadika','Zehić','Ž',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('mineta_hadzaga','Mineta','Zehić','Ž',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('asmir_hadzaga','Asmir','Zehić','M',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('amra_asmir','Amra','Zehić','Ž',6,'Grana Adem','','','asmir_hadzaga','Asmir','','',0);
INSERT INTO "clanovi" VALUES('amir_asmir','Amir','Zehić','M',6,'Grana Adem','','','asmir_hadzaga','Asmir','','',0);
INSERT INTO "clanovi" VALUES('azra_hadzaga','Azra','Zehić','Ž',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('zikreta_hadzaga','Zikreta','Zehić','Ž',5,'Grana Adem','','','hadzaga_mujo','Hadžaga','','',0);
INSERT INTO "clanovi" VALUES('saban_mujo','Šaban','Zehić','M',4,'Grana Adem','','','mujo_adem','Mujo','','',0);
INSERT INTO "clanovi" VALUES('dzemila_mujo','Džemila','Zehić','Ž',4,'Grana Adem','','','mujo_adem','Mujo','','',0);
INSERT INTO "clanovi" VALUES('sp_harnaga_mujo','Hatidža','','Ž',4,'Grana Adem','','Supruga','harnaga_mujo','Harnaga','Harnaga','',1);
INSERT INTO "clanovi" VALUES('harnaga_mujo','Harnaga','Zehić','M',4,'Grana Adem','','','mujo_adem','Mujo','Hatidža','Supruga',0);
INSERT INTO "clanovi" VALUES('halida_harnaga','Halida','Zehić','Ž',5,'Grana Adem','','u. Smajić','harnaga_mujo','Harnaga','','',0);
INSERT INTO "clanovi" VALUES('dzemila_harnaga','Džemila','Zehić','Ž',5,'Grana Adem','','u. Haić','harnaga_mujo','Harnaga','','',0);
INSERT INTO "clanovi" VALUES('izeta_harnaga','Izeta','Zehić','Ž',5,'Grana Adem','','','harnaga_mujo','Harnaga','','',0);
INSERT INTO "clanovi" VALUES('izet_harnaga','Izet','Zehić','M',5,'Grana Adem','','','harnaga_mujo','Harnaga','','',0);
INSERT INTO "clanovi" VALUES('admir_izet_h','Admir','Zehić','M',6,'Grana Adem','','','izet_harnaga','Izet','','',0);
INSERT INTO "clanovi" VALUES('emrah_admir_h','Emrah','Zehić','M',7,'Grana Adem','','','admir_izet_h','Admir','','',0);
INSERT INTO "clanovi" VALUES('emina_admir_h','Emina','Zehić','Ž',7,'Grana Adem','','','admir_izet_h','Admir','','',0);
INSERT INTO "clanovi" VALUES('sabina_izet_h','Sabina','Zehić','Ž',6,'Grana Adem','','','izet_harnaga','Izet','','',0);
INSERT INTO "clanovi" VALUES('emina_izet_h','Emina','Zehić','Ž',6,'Grana Adem','','','izet_harnaga','Izet','','',0);
INSERT INTO "clanovi" VALUES('haris_izet_h','Haris','Zehić','M',6,'Grana Adem','','','izet_harnaga','Izet','','',0);
INSERT INTO "clanovi" VALUES('benjamin_haris','Benjamin','Zehić','M',7,'Grana Adem','','','haris_izet_h','Haris','','',0);
INSERT INTO "clanovi" VALUES('hana_haris','Hana','Zehić','Ž',7,'Grana Adem','','','haris_izet_h','Haris','','',0);
INSERT INTO "clanovi" VALUES('sp_sajtan_adem','Zemina','','Ž',3,'Grana Adem','','r. Bešići','sajtan_adem','Sajtan','Sajtan','',1);
INSERT INTO "clanovi" VALUES('sajtan_adem','Sajtan','Zehić','M',3,'Grana Adem','','','adem_1','Adem','Zemina','r. Bešići',0);
INSERT INTO "clanovi" VALUES('sp_began_sajtan','Zilka','','Ž',4,'Grana Adem','','Supruga','began_sajtan','Began','Began','',1);
INSERT INTO "clanovi" VALUES('began_sajtan','Began','Zehić','M',4,'Grana Adem','','','sajtan_adem','Sajtan','Zilka','Supruga',0);
INSERT INTO "clanovi" VALUES('begajeta_began','Begajeta','Zehić','Ž',5,'Grana Adem','','','began_sajtan','Began','','',0);
INSERT INTO "clanovi" VALUES('biba_began','Biba','Zehić','Ž',5,'Grana Adem','','','began_sajtan','Began','','',0);
INSERT INTO "clanovi" VALUES('sefik_began','Šefik','Zehić','M',5,'Grana Adem','','','began_sajtan','Began','','',0);
INSERT INTO "clanovi" VALUES('amela_sefik','Amela','Zehić','Ž',6,'Grana Adem','','','sefik_began','Šefik','','',0);
INSERT INTO "clanovi" VALUES('jasmin_sefik','Jasmin','Zehić','M',6,'Grana Adem','','','sefik_began','Šefik','','',0);
INSERT INTO "clanovi" VALUES('sp_mustafa_sajtan','Šuhra','','Ž',4,'Grana Adem','','Supruga','mustafa_sajtan','Mustafa','Mustafa','',1);
INSERT INTO "clanovi" VALUES('mustafa_sajtan','Mustafa','Zehić','M',4,'Grana Adem','','','sajtan_adem','Sajtan','Šuhra','Supruga',0);
INSERT INTO "clanovi" VALUES('saban_mustafa','Šaban','Zehić','M',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('azra_saban_m','Azra','Zehić','Ž',6,'Grana Adem','','','saban_mustafa','Šaban','','',0);
INSERT INTO "clanovi" VALUES('aida_saban_m','Aida','Zehić','Ž',6,'Grana Adem','','','saban_mustafa','Šaban','','',0);
INSERT INTO "clanovi" VALUES('zemina_mustafa','Zemina','Zehić','Ž',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('hasiba_mustafa','Hasiba','Zehić','Ž',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('sumbila_mustafa','Sumbila','Zehić','Ž',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('sena_mustafa','Sena','Zehić','Ž',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('bekrija_mustafa','Bekrija','Zehić','M',5,'Grana Adem','','','mustafa_sajtan','Mustafa','','',0);
INSERT INTO "clanovi" VALUES('selma_bekrija','Selma','Zehić','Ž',6,'Grana Adem','','','bekrija_mustafa','Bekrija','','',0);
INSERT INTO "clanovi" VALUES('vahida_bekrija','Vahida','Zehić','Ž',6,'Grana Adem','','','bekrija_mustafa','Bekrija','','',0);
INSERT INTO "clanovi" VALUES('vahidin_bekrija','Vahidin','Zehić','M',6,'Grana Adem','','','bekrija_mustafa','Bekrija','','',0);
INSERT INTO "clanovi" VALUES('kcerka_sajtan','Kćerka','Zehić','Ž',4,'Grana Adem','','(Non nommée)','sajtan_adem','Sajtan','','',0);
INSERT INTO "clanovi" VALUES('fata_sajtan','Fata','Zehić','Ž',4,'Grana Adem','','','sajtan_adem','Sajtan','','',0);
INSERT INTO "clanovi" VALUES('sp_ismet_sajtan','Hajrija','','Ž',4,'Grana Adem','','Supruga','ismet_sajtan','Ismet','Ismet','',1);
INSERT INTO "clanovi" VALUES('ismet_sajtan','Ismet','Zehić','M',4,'Grana Adem','','','sajtan_adem','Sajtan','Hajrija','Supruga',0);
INSERT INTO "clanovi" VALUES('izet_sajtan','Izet','Zehić','M',5,'Grana Adem','','','ismet_sajtan','Ismet','','',0);
INSERT INTO "clanovi" VALUES('senada_izet_s','Senada','Zehić','Ž',6,'Grana Adem','','','izet_sajtan','Izet','','',0);
INSERT INTO "clanovi" VALUES('senad_izet_s','Senad','Zehić','M',6,'Grana Adem','','','izet_sajtan','Izet','','',0);
INSERT INTO "clanovi" VALUES('ajla_senad_s','Ajla','Zehić','Ž',7,'Grana Adem','','','senad_izet_s','Senad','','',0);
INSERT INTO "clanovi" VALUES('najla_senad_s','Najla','Zehić','Ž',7,'Grana Adem','','','senad_izet_s','Senad','','',0);
INSERT INTO "clanovi" VALUES('muzijet_sajtan','Muzijet','Zehić','M',5,'Grana Adem','','','ismet_sajtan','Ismet','','',0);
INSERT INTO "clanovi" VALUES('almir_muzijet','Almir','Zehić','M',6,'Grana Adem','','','muzijet_sajtan','Muzijet','','',0);
INSERT INTO "clanovi" VALUES('anela_almir_m','Anela','Zehić','Ž',7,'Grana Adem','','','almir_muzijet','Almir','','',0);
INSERT INTO "clanovi" VALUES('admir_muzijet','Admir','Zehić','M',6,'Grana Adem','','','muzijet_sajtan','Muzijet','','',0);
INSERT INTO "clanovi" VALUES('dalila_admir_m','Dalila','Zehić','Ž',7,'Grana Adem','','','admir_muzijet','Admir','','',0);
INSERT INTO "clanovi" VALUES('ilda_admir_m','Ilda','Zehić','Ž',7,'Grana Adem','','','admir_muzijet','Admir','','',0);
INSERT INTO "clanovi" VALUES('selima_sajtan','Selima','Zehić','Ž',4,'Grana Adem','','','sajtan_adem','Sajtan','','',0);
INSERT INTO "clanovi" VALUES('fatima_sajtan','Fatima','Zehić','Ž',4,'Grana Adem','','','sajtan_adem','Sajtan','','',0);
INSERT INTO "clanovi" VALUES('sp_ibrahim_adem','Rukija','','Ž',3,'Grana Adem','','r. Brčko','ibrahim_adem','Ibrahim','Ibrahim','',1);
INSERT INTO "clanovi" VALUES('ibrahim_adem','Ibrahim','Zehić','M',3,'Grana Adem','','','adem_1','Adem','Rukija','r. Brčko',0);
INSERT INTO "clanovi" VALUES('sp_pasaga_ibrahim','Nesiba','','Ž',4,'Grana Adem','','r. Bešići','pasaga_ibrahim','Pašaga','Pašaga','',1);
INSERT INTO "clanovi" VALUES('pasaga_ibrahim','Pašaga','Zehić','M',4,'Grana Adem','','','ibrahim_adem','Ibrahim','Nesiba','r. Bešići',0);
INSERT INTO "clanovi" VALUES('sp_ibrahim_pasaga','Mina','','Ž',5,'Grana Adem','','r. T. Brdo','ibrahim_pasaga','Ibrahim','Ibrahim','',1);
INSERT INTO "clanovi" VALUES('ibrahim_pasaga','Ibrahim','Zehić','M',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','Mina','r. T. Brdo',0);
INSERT INTO "clanovi" VALUES('amira_ibrahim_p','Amira','Zehić','Ž',6,'Grana Adem','','','ibrahim_pasaga','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('bahira_ibrahim_p','Bahira','Zehić','Ž',6,'Grana Adem','','','ibrahim_pasaga','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('sahza_ibrahim_p','Šahza','Zehić','Ž',6,'Grana Adem','','','ibrahim_pasaga','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('mina_pasaga','Mina','Zehić','Ž',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','','',0);
INSERT INTO "clanovi" VALUES('muniba_pasaga','Muniba','Zehić','Ž',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','','',0);
INSERT INTO "clanovi" VALUES('rukija_pasaga','Rukija','Zehić','Ž',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','','',0);
INSERT INTO "clanovi" VALUES('tima_pasaga','Tima','Zehić','Ž',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','','',0);
INSERT INTO "clanovi" VALUES('sp_cido_pasaga','Ramiza','','Ž',5,'Grana Adem','','Supruga','cido_pasaga','Ćido','Ćido','',1);
INSERT INTO "clanovi" VALUES('cido_pasaga','Ćido','Zehić','M',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','Ramiza','Supruga',0);
INSERT INTO "clanovi" VALUES('jasmina_cido','Jasmina','Zehić','Ž',6,'Grana Adem','','','cido_pasaga','Ćido','','',0);
INSERT INTO "clanovi" VALUES('azemina_cido','Azemina','Zehić','Ž',6,'Grana Adem','','','cido_pasaga','Ćido','','',0);
INSERT INTO "clanovi" VALUES('sp_halil_pasaga','Mina','','Ž',5,'Grana Adem','','Supruga','halil_pasaga','Halil','Halil','',1);
INSERT INTO "clanovi" VALUES('halil_pasaga','Halil','Zehić','M',5,'Grana Adem','','','pasaga_ibrahim','Pašaga','Mina','Supruga',0);
INSERT INTO "clanovi" VALUES('nedzad_halil_p','Nedžad','Zehić','M',6,'Grana Adem','','','halil_pasaga','Halil','','',0);
INSERT INTO "clanovi" VALUES('erna_nedzad_h','Erna','Zehić','Ž',7,'Grana Adem','','','nedzad_halil_p','Nedžad','','',0);
INSERT INTO "clanovi" VALUES('lejla_nedzad_h','Lejla','Zehić','Ž',7,'Grana Adem','','','nedzad_halil_p','Nedžad','','',0);
INSERT INTO "clanovi" VALUES('nesad_halil_p','Nešad','Zehić','M',6,'Grana Adem','','','halil_pasaga','Halil','','',0);
INSERT INTO "clanovi" VALUES('armina_nesad_h','Armina','Zehić','Ž',7,'Grana Adem','','','nesad_halil_p','Nešad','','',0);
INSERT INTO "clanovi" VALUES('armin_nesad_h','Armin','Zehić','M',7,'Grana Adem','','','nesad_halil_p','Nešad','','',0);
INSERT INTO "clanovi" VALUES('benjamin_armin_h','Benjamin','Zehić','M',8,'Grana Adem','','','armin_nesad_h','Armin','','',0);
INSERT INTO "clanovi" VALUES('adem_armin_h','Adem','Zehić','M',8,'Grana Adem','','','armin_nesad_h','Armin','','',0);
INSERT INTO "clanovi" VALUES('adem_ibrahim_a','Adem','Zehić','M',4,'Grana Adem','','n. Poginuo','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('halil_ibrahim_a','Halil','Zehić','M',4,'Grana Adem','','n. Poginuo','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('zumra_ibrahim_a','Zumra','Zehić','Ž',4,'Grana Adem','','','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('sevka_ibrahim_a','Ševka','Zehić','Ž',4,'Grana Adem','','','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('izeta_ibrahim_a','Izeta','Zehić','Ž',4,'Grana Adem','','','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('zineta_ibrahim_a','Zineta','Zehić','Ž',4,'Grana Adem','','','ibrahim_adem','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('sp_atlaga_ibrahim_a','Munira','','Ž',4,'Grana Adem','','r. Bilalići','atlaga_ibrahim_a','Atlaga','Atlaga','',1);
INSERT INTO "clanovi" VALUES('atlaga_ibrahim_a','Atlaga','Zehić','M',4,'Grana Adem','','','ibrahim_adem','Ibrahim','Munira','r. Bilalići',0);
INSERT INTO "clanovi" VALUES('sp_nuraga_atlaga','Elvira','','Ž',5,'Grana Adem','','Supruga','nuraga_atlaga','Nuraga','Nuraga','',1);
INSERT INTO "clanovi" VALUES('nuraga_atlaga','Nuraga','Zehić','M',5,'Grana Adem','','','atlaga_ibrahim_a','Atlaga','Elvira','Supruga',0);
INSERT INTO "clanovi" VALUES('azra_nuraga','Azra','Zehić','Ž',6,'Grana Adem','','','nuraga_atlaga','Nuraga','','',0);
INSERT INTO "clanovi" VALUES('aida_nuraga','Aida','Zehić','Ž',6,'Grana Adem','','','nuraga_atlaga','Nuraga','','',0);
INSERT INTO "clanovi" VALUES('kada_atlaga','Kada','Zehić','Ž',5,'Grana Adem','','','atlaga_ibrahim_a','Atlaga','','',0);
INSERT INTO "clanovi" VALUES('suada_atlaga','Suada','Zehić','Ž',5,'Grana Adem','','','atlaga_ibrahim_a','Atlaga','','',0);
INSERT INTO "clanovi" VALUES('sp_adem_atlaga','Velida','','Ž',5,'Grana Adem','','Supruga','adem_atlaga','Adem','Adem','',1);
INSERT INTO "clanovi" VALUES('adem_atlaga','Adem','Zehić','M',5,'Grana Adem','','','atlaga_ibrahim_a','Atlaga','Velida','Supruga',0);
INSERT INTO "clanovi" VALUES('adisa_adem_at','Adisa','Zehić','Ž',6,'Grana Adem','','','adem_atlaga','Adem','','',0);
INSERT INTO "clanovi" VALUES('admir_adem_at','Admir','Zehić','M',6,'Grana Adem','','','adem_atlaga','Adem','','',0);
INSERT INTO "clanovi" VALUES('beslaga_atlaga','Bešlaga','Zehić','M',5,'Grana Adem','','','atlaga_ibrahim_a','Atlaga','','',0);
INSERT INTO "clanovi" VALUES('edin_beslaga','Edin','Zehić','M',6,'Grana Adem','','','beslaga_atlaga','Bešlaga','','',0);
INSERT INTO "clanovi" VALUES('sumeja_edin_b','Sumeja','Zehić','Ž',7,'Grana Adem','','','edin_beslaga','Edin','','',0);
INSERT INTO "clanovi" VALUES('harun_edin_b','Harun','Zehić','M',7,'Grana Adem','','','edin_beslaga','Edin','','',0);
INSERT INTO "clanovi" VALUES('enver_beslaga','Enver','Zehić','M',6,'Grana Adem','','','beslaga_atlaga','Bešlaga','','',0);
INSERT INTO "clanovi" VALUES('ismail_beslaga','Ismail','Zehić','M',6,'Grana Adem','','','beslaga_atlaga','Bešlaga','','',0);
INSERT INTO "clanovi" VALUES('amina_beslaga','Amina','Zehić','Ž',6,'Grana Adem','','','beslaga_atlaga','Bešlaga','','',0);
INSERT INTO "clanovi" VALUES('omer_beslaga','Omer','Zehić','M',6,'Grana Adem','','','beslaga_atlaga','Bešlaga','','',0);
INSERT INTO "clanovi" VALUES('sp_meho_1','Cura','','Ž',2,'Grana Meho','','Supruga','meho_1','Meho','Meho','',1);
INSERT INTO "clanovi" VALUES('meho_1','Meho','Zehić','M',2,'Grana Meho','1867 – 1941','','ibrahim_root','Ibrahim','Cura','Supruga',0);
INSERT INTO "clanovi" VALUES('mehmed_meho','Mehmed','Zehić','M',3,'Grana Meho','1903 – 1945','','meho_1','Meho','','',0);
INSERT INTO "clanovi" VALUES('sp_bijader_mehmed_m','Zumreta','','Ž',4,'Grana Meho','','Supruga','bijader_mehmed_m','Bijader','Bijader','',1);
INSERT INTO "clanovi" VALUES('bijader_mehmed_m','Bijader','Zehić','M',4,'Grana Meho','','','mehmed_meho','Mehmed','Zumreta','Supruga',0);
INSERT INTO "clanovi" VALUES('mensura_bijader','Mensura','Zehić','Ž',5,'Grana Meho','','','bijader_mehmed_m','Bijader','','',0);
INSERT INTO "clanovi" VALUES('mirsad_bijader','Mirsad','Zehić','M',5,'Grana Meho','','','bijader_mehmed_m','Bijader','','',0);
INSERT INTO "clanovi" VALUES('sp_mehmed_bijader','Zumra','','Ž',5,'Grana Meho','','Supruga','mehmed_bijader','Mehmed','Mehmed','',1);
INSERT INTO "clanovi" VALUES('mehmed_bijader','Mehmed','Zehić','M',5,'Grana Meho','','','bijader_mehmed_m','Bijader','Zumra','Supruga',0);
INSERT INTO "clanovi" VALUES('meliha_mehmed_b','Meliha','Zehić','Ž',6,'Grana Meho','','','mehmed_bijader','Mehmed','','',0);
INSERT INTO "clanovi" VALUES('emina_mehmed_b','Emina','Zehić','Ž',6,'Grana Meho','','','mehmed_bijader','Mehmed','','',0);
INSERT INTO "clanovi" VALUES('velida_mehmed_m','Velida','Zehić','Ž',4,'Grana Meho','','','mehmed_meho','Mehmed','','',0);
INSERT INTO "clanovi" VALUES('fadila_mehmed_m','Fadila','Zehić','Ž',4,'Grana Meho','','','mehmed_meho','Mehmed','','',0);
INSERT INTO "clanovi" VALUES('velid_mehmed_m','Velid','Zehić','M',4,'Grana Meho','','','mehmed_meho','Mehmed','','',0);
INSERT INTO "clanovi" VALUES('sp_zedin_mehmed_m','Zilka','','Ž',4,'Grana Meho','','Supruga','zedin_mehmed_m','Zedin','Zedin','',1);
INSERT INTO "clanovi" VALUES('zedin_mehmed_m','Zedin','Zehić','M',4,'Grana Meho','','','mehmed_meho','Mehmed','Zilka','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_velid_zedin','Marica','','Ž',5,'Grana Meho','','Supruga','velid_zedin','Velid','Velid','',1);
INSERT INTO "clanovi" VALUES('velid_zedin','Velid','Zehić','M',5,'Grana Meho','','','zedin_mehmed_m','Zedin','Marica','Supruga',0);
INSERT INTO "clanovi" VALUES('nenad_velid_z','Nenad','Zehić','M',6,'Grana Meho','','','velid_zedin','Velid','','',0);
INSERT INTO "clanovi" VALUES('senad_velid_z','Senad','Zehić','M',6,'Grana Meho','','','velid_zedin','Velid','','',0);
INSERT INTO "clanovi" VALUES('zineta_zedin','Zineta','Zehić','Ž',5,'Grana Meho','','','zedin_mehmed_m','Zedin','','',0);
INSERT INTO "clanovi" VALUES('zehrija_zedin','Zehrija','Zehić','Ž',5,'Grana Meho','','','zedin_mehmed_m','Zedin','','',0);
INSERT INTO "clanovi" VALUES('sp_zehrudin_zedin','Elvira','','Ž',5,'Grana Meho','','Supruga','zehrudin_zedin','Zehrudin','Zehrudin','',1);
INSERT INTO "clanovi" VALUES('zehrudin_zedin','Zehrudin','Zehić','M',5,'Grana Meho','','','zedin_mehmed_m','Zedin','Elvira','Supruga',0);
INSERT INTO "clanovi" VALUES('samira_zehrudin','Samira','Zehić','Ž',6,'Grana Meho','','','zehrudin_zedin','Zehrudin','','',0);
INSERT INTO "clanovi" VALUES('alisa_zehrudin','Alisa','Zehić','Ž',6,'Grana Meho','','','zehrudin_zedin','Zehrudin','','',0);
INSERT INTO "clanovi" VALUES('elvis_zehrudin','Elvis','Zehić','M',6,'Grana Meho','','','zehrudin_zedin','Zehrudin','','',0);
INSERT INTO "clanovi" VALUES('sp_sinan_meho','Aiša','','Ž',3,'Grana Meho','','Supruga','sinan_meho','Sinan','Sinan','',1);
INSERT INTO "clanovi" VALUES('sinan_meho','Sinan','Zehić','M',3,'Grana Meho','1907 – 1984','','meho_1','Meho','Aiša','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_asim_sinan','Zorka','','Ž',4,'Grana Meho','','Supruga','asim_sinan','Asim','Asim','',1);
INSERT INTO "clanovi" VALUES('asim_sinan','Asim','Zehić','M',4,'Grana Meho','','','sinan_meho','Sinan','Zorka','Supruga',0);
INSERT INTO "clanovi" VALUES('jasmina_asim','Jasmina','Zehić','Ž',5,'Grana Meho','','','asim_sinan','Asim','','',0);
INSERT INTO "clanovi" VALUES('sp_rasid_sinan','Kaima','','Ž',4,'Grana Meho','','Supruga','rasid_sinan','Rašid','Rašid','',1);
INSERT INTO "clanovi" VALUES('rasid_sinan','Rašid','Zehić','M',4,'Grana Meho','','','sinan_meho','Sinan','Kaima','Supruga',0);
INSERT INTO "clanovi" VALUES('lejla_rasid','Lejla','Zehić','Ž',5,'Grana Meho','','','rasid_sinan','Rašid','','',0);
INSERT INTO "clanovi" VALUES('jasmin_rasid','Jasmin','Zehić','M',5,'Grana Meho','','','rasid_sinan','Rašid','','',0);
INSERT INTO "clanovi" VALUES('kaima_jasmin_r','Kaima','Zehić','Ž',6,'Grana Meho','','','jasmin_rasid','Jasmin','','',0);
INSERT INTO "clanovi" VALUES('kemal_jasmin_r','Kemal','Zehić','M',6,'Grana Meho','','','jasmin_rasid','Jasmin','','',0);
INSERT INTO "clanovi" VALUES('sp_ahmo_sinan','Hiba','','Ž',4,'Grana Meho','','Supruga','ahmo_sinan','Ahmo','Ahmo','',1);
INSERT INTO "clanovi" VALUES('ahmo_sinan','Ahmo','Zehić','M',4,'Grana Meho','','','sinan_meho','Sinan','Hiba','Supruga',0);
INSERT INTO "clanovi" VALUES('hida_ahmo','Hida','Zehić','M',5,'Grana Meho','','','ahmo_sinan','Ahmo','','',0);
INSERT INTO "clanovi" VALUES('sp_nijaz_ahmo','Arifa','','Ž',5,'Grana Meho','','Supruga','nijaz_ahmo','Nijaz','Nijaz','',1);
INSERT INTO "clanovi" VALUES('nijaz_ahmo','Nijaz','Zehić','M',5,'Grana Meho','','','ahmo_sinan','Ahmo','Arifa','Supruga',0);
INSERT INTO "clanovi" VALUES('ervin_nijaz_a','Ervin','Zehić','M',6,'Grana Meho','','','nijaz_ahmo','Nijaz','','',0);
INSERT INTO "clanovi" VALUES('safa_sinan','Safa','Zehić','Ž',4,'Grana Meho','','','sinan_meho','Sinan','','',0);
INSERT INTO "clanovi" VALUES('sp_esad_sinan','Nesiba','','Ž',4,'Grana Meho','','Supruga','esad_sinan','Esad','Esad','',1);
INSERT INTO "clanovi" VALUES('esad_sinan','Esad','Zehić','M',4,'Grana Meho','','','sinan_meho','Sinan','Nesiba','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_safet_esad','Maida','','Ž',5,'Grana Meho','','Supruga','safet_esad','Safet','Safet','',1);
INSERT INTO "clanovi" VALUES('safet_esad','Safet','Zehić','M',5,'Grana Meho','','','esad_sinan','Esad','Maida','Supruga',0);
INSERT INTO "clanovi" VALUES('sabina_safet','Sabina','Zehić','Ž',6,'Grana Meho','','','safet_esad','Safet','','',0);
INSERT INTO "clanovi" VALUES('emir_safet','Emir','Zehić','M',6,'Grana Meho','','','safet_esad','Safet','','',0);
INSERT INTO "clanovi" VALUES('semir_safet','Semir','Zehić','M',6,'Grana Meho','','','safet_esad','Safet','','',0);
INSERT INTO "clanovi" VALUES('sp_ahmet_esad','Mejrema','','Ž',5,'Grana Meho','','Supruga','ahmet_esad','Ahmet','Ahmet','',1);
INSERT INTO "clanovi" VALUES('ahmet_esad','Ahmet','Zehić','M',5,'Grana Meho','','','esad_sinan','Esad','Mejrema','Supruga',0);
INSERT INTO "clanovi" VALUES('mirsad_ahmet','Mirsad','Zehić','M',6,'Grana Meho','','','ahmet_esad','Ahmet','','',0);
INSERT INTO "clanovi" VALUES('mensur_ahmet','Mensur','Zehić','M',6,'Grana Meho','','','ahmet_esad','Ahmet','','',0);
INSERT INTO "clanovi" VALUES('mejra_meho','Mejra','Zehić','Ž',3,'Grana Meho','','','meho_1','Meho','','',0);
INSERT INTO "clanovi" VALUES('sp_huso_meho','Hanka','','Ž',3,'Grana Meho','','Supruga','huso_meho','Huso','Huso','',1);
INSERT INTO "clanovi" VALUES('huso_meho','Huso','Zehić','M',3,'Grana Meho','1913 – 1998','','meho_1','Meho','Hanka','Supruga',0);
INSERT INTO "clanovi" VALUES('pasa_huso','Paša','Zehić','Ž',4,'Grana Meho','','','huso_meho','Huso','','',0);
INSERT INTO "clanovi" VALUES('nura_huso','Nura','Zehić','Ž',4,'Grana Meho','','','huso_meho','Huso','','',0);
INSERT INTO "clanovi" VALUES('zemina_huso','Zemina','Zehić','Ž',4,'Grana Meho','','','huso_meho','Huso','','',0);
INSERT INTO "clanovi" VALUES('sp_mehan_huso','Fadila','','Ž',4,'Grana Meho','','Supruga','mehan_huso','Mehan','Mehan','',1);
INSERT INTO "clanovi" VALUES('mehan_huso','Mehan','Zehić','M',4,'Grana Meho','','','huso_meho','Huso','Fadila','Supruga',0);
INSERT INTO "clanovi" VALUES('mevlida_mehan','Mevlida','Zehić','Ž',5,'Grana Meho','','','mehan_huso','Mehan','','',0);
INSERT INTO "clanovi" VALUES('eldina_mehan','Eldina','Zehić','Ž',5,'Grana Meho','','','mehan_huso','Mehan','','',0);
INSERT INTO "clanovi" VALUES('sp_mensur_mehan','Nermina','','Ž',5,'Grana Meho','','Supruga','mensur_mehan','Mensur','Mensur','',1);
INSERT INTO "clanovi" VALUES('mensur_mehan','Mensur','Zehić','M',5,'Grana Meho','','','mehan_huso','Mehan','Nermina','Supruga',0);
INSERT INTO "clanovi" VALUES('ajla_mensur_m','Ajla','Zehić','Ž',6,'Grana Meho','','','mensur_mehan','Mensur','','',0);
INSERT INTO "clanovi" VALUES('lejla_mensur_m','Lejla','Zehić','Ž',6,'Grana Meho','','','mensur_mehan','Mensur','','',0);
INSERT INTO "clanovi" VALUES('sp_osman_1','Hata','','Ž',2,'Grana Osman','','Supruga','osman_1','Osman','Osman','',1);
INSERT INTO "clanovi" VALUES('osman_1','Osman','Zehić','M',2,'Grana Osman','1860 – 1937','','ibrahim_root','Ibrahim','Hata','Supruga',0);
INSERT INTO "clanovi" VALUES('fatima_osman_luke','Fatima','Zehić','Ž',3,'Grana Osman','','u. Luke','osman_1','Osman','','',0);
INSERT INTO "clanovi" VALUES('sp_avdo_osman','Mejra','','Ž',3,'Grana Osman','','Supruga','avdo_osman','Avdo','Avdo','',1);
INSERT INTO "clanovi" VALUES('avdo_osman','Avdo','Zehić','M',3,'Grana Osman','1887 – 1942','','osman_1','Osman','Mejra','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_sukrija_avdo_o','Fehma','','Ž',4,'Grana Osman','','Supruga','sukrija_avdo_o','Šukrija','Šukrija','',1);
INSERT INTO "clanovi" VALUES('sukrija_avdo_o','Šukrija','Zehić','M',4,'Grana Osman','','','avdo_osman','Avdo','Fehma','Supruga',0);
INSERT INTO "clanovi" VALUES('azra_sukrija','Azra','Zehić','Ž',5,'Grana Osman','','','sukrija_avdo_o','Šukrija','','',0);
INSERT INTO "clanovi" VALUES('nijaz_sukrija','Nijaz','Zehić','M',5,'Grana Osman','','','sukrija_avdo_o','Šukrija','','',0);
INSERT INTO "clanovi" VALUES('alen_nijaz_s','Alen','Zehić','M',6,'Grana Osman','','','nijaz_sukrija','Nijaz','','',0);
INSERT INTO "clanovi" VALUES('admir_nijaz_s','Admir','Zehić','M',6,'Grana Osman','','','nijaz_sukrija','Nijaz','','',0);
INSERT INTO "clanovi" VALUES('mehmed_avdo_o','Mehmed','Zehić','M',4,'Grana Osman','','n. Poginuo u saobraćajnoj nesreći','avdo_osman','Avdo','','',0);
INSERT INTO "clanovi" VALUES('sp_omer_avdo_o','Fatima','','Ž',4,'Grana Osman','','Supruga','omer_avdo_o','Omer','Omer','',1);
INSERT INTO "clanovi" VALUES('omer_avdo_o','Omer','Zehić','M',4,'Grana Osman','','','avdo_osman','Avdo','Fatima','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_salkan_avdo_o','Havka','','Ž',4,'Grana Osman','','Supruga','salkan_avdo_o','Salkan','Salkan','',1);
INSERT INTO "clanovi" VALUES('salkan_avdo_o','Salkan','Zehić','M',4,'Grana Osman','','','avdo_osman','Avdo','Havka','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_zekerijah_salkan','Mina','','Ž',5,'Grana Osman','','Supruga','zekerijah_salkan','Zekerijah','Zekerijah','',1);
INSERT INTO "clanovi" VALUES('zekerijah_salkan','Zekerijah','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','Mina','Supruga',0);
INSERT INTO "clanovi" VALUES('mersudin_zekerijah','Mersudin','Zehić','M',6,'Grana Osman','','','zekerijah_salkan','Zekerijah','','',0);
INSERT INTO "clanovi" VALUES('majda_mersudin','Majda','Zehić','Ž',7,'Grana Osman','','','mersudin_zekerijah','Mersudin','','',0);
INSERT INTO "clanovi" VALUES('adi_mersudin','Adi','Zehić','M',7,'Grana Osman','','','mersudin_zekerijah','Mersudin','','',0);
INSERT INTO "clanovi" VALUES('sp_avdo_salkan','Zumreta','','Ž',5,'Grana Osman','','Supruga','avdo_salkan','Avdo','Avdo','',1);
INSERT INTO "clanovi" VALUES('avdo_salkan','Avdo','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','Zumreta','Supruga',0);
INSERT INTO "clanovi" VALUES('aida_avdo_s','Aida','Zehić','Ž',6,'Grana Osman','','','avdo_salkan','Avdo','','',0);
INSERT INTO "clanovi" VALUES('larisa_avdo_s','Larisa','Zehić','Ž',6,'Grana Osman','','','avdo_salkan','Avdo','','',0);
INSERT INTO "clanovi" VALUES('vahid_avdo_s','Vahid','Zehić','M',6,'Grana Osman','','','avdo_salkan','Avdo','','',0);
INSERT INTO "clanovi" VALUES('alina_vahid','Alina','Zehić','Ž',7,'Grana Osman','','','vahid_avdo_s','Vahid','','',0);
INSERT INTO "clanovi" VALUES('ajla_vahid','Ajla','Zehić','Ž',7,'Grana Osman','','','vahid_avdo_s','Vahid','','',0);
INSERT INTO "clanovi" VALUES('zekija_salkan','Zekija','Zehić','Ž',5,'Grana Osman','','','salkan_avdo_o','Salkan','','',0);
INSERT INTO "clanovi" VALUES('sp_sevludin_salkan','Sekija','','Ž',5,'Grana Osman','','Supruga','sevludin_salkan','Sevludin','Sevludin','',1);
INSERT INTO "clanovi" VALUES('sevludin_salkan','Sevludin','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','Sekija','Supruga',0);
INSERT INTO "clanovi" VALUES('adisa_sevludin','Adisa','Zehić','Ž',6,'Grana Osman','','','sevludin_salkan','Sevludin','','',0);
INSERT INTO "clanovi" VALUES('amela_sevludin','Amela','Zehić','Ž',6,'Grana Osman','','','sevludin_salkan','Sevludin','','',0);
INSERT INTO "clanovi" VALUES('enes_salkan','Enes','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','','',0);
INSERT INTO "clanovi" VALUES('bego_salkan','Bego','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','','',0);
INSERT INTO "clanovi" VALUES('mirsad_salkan','Mirsad','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','','',0);
INSERT INTO "clanovi" VALUES('sp_muhidin_salkan','Sabina','','Ž',5,'Grana Osman','','Supruga','muhidin_salkan','Muhidin','Muhidin','',1);
INSERT INTO "clanovi" VALUES('muhidin_salkan','Muhidin','Zehić','M',5,'Grana Osman','','','salkan_avdo_o','Salkan','Sabina','Supruga',0);
INSERT INTO "clanovi" VALUES('sanela_muhidin','Sanela','Zehić','Ž',6,'Grana Osman','','','muhidin_salkan','Muhidin','','',0);
INSERT INTO "clanovi" VALUES('jasmin_muhidin','Jasmin','Zehić','M',6,'Grana Osman','','','muhidin_salkan','Muhidin','','',0);
INSERT INTO "clanovi" VALUES('sp_sahbaz_osman','Emka','','Ž',3,'Grana Osman','','Supruga','sahbaz_osman','Šahbaz','Šahbaz','',1);
INSERT INTO "clanovi" VALUES('sahbaz_osman','Šahbaz','Zehić','M',3,'Grana Osman','1910 – 1998','','osman_1','Osman','Emka','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_osman_sahbaz','Nura','','Ž',4,'Grana Osman','','Supruga','osman_sahbaz','Osman','Osman','',1);
INSERT INTO "clanovi" VALUES('osman_sahbaz','Osman','Zehić','M',4,'Grana Osman','','','sahbaz_osman','Šahbaz','Nura','Supruga',0);
INSERT INTO "clanovi" VALUES('vaila_osman_s','Vaila','Zehić','Ž',5,'Grana Osman','','','osman_sahbaz','Osman','','',0);
INSERT INTO "clanovi" VALUES('zekira_osman_s','Zekira','Zehić','Ž',5,'Grana Osman','','','osman_sahbaz','Osman','','',0);
INSERT INTO "clanovi" VALUES('azra_osman_s','Azra','Zehić','Ž',5,'Grana Osman','','','osman_sahbaz','Osman','','',0);
INSERT INTO "clanovi" VALUES('sp_sevko_sahbaz','Džemila','','Ž',4,'Grana Osman','','Supruga','sevko_sahbaz','Ševko','Ševko','',1);
INSERT INTO "clanovi" VALUES('sevko_sahbaz','Ševko','Zehić','M',4,'Grana Osman','','','sahbaz_osman','Šahbaz','Džemila','Supruga',0);
INSERT INTO "clanovi" VALUES('nermin_sevko','Nermin','Zehić','M',5,'Grana Osman','','','sevko_sahbaz','Ševko','','',0);
INSERT INTO "clanovi" VALUES('benjamin_nermin_s','Benjamin','Zehić','M',6,'Grana Osman','','','nermin_sevko','Nermin','','',0);
INSERT INTO "clanovi" VALUES('albin_nermin_s','Albin','Zehić','M',6,'Grana Osman','','','nermin_sevko','Nermin','','',0);
INSERT INTO "clanovi" VALUES('elvedina_sevko','Elvedina','Zehić','Ž',5,'Grana Osman','','','sevko_sahbaz','Ševko','','',0);
INSERT INTO "clanovi" VALUES('elvedin_sevko','Elvedin','Zehić','M',5,'Grana Osman','','','sevko_sahbaz','Ševko','','',0);
INSERT INTO "clanovi" VALUES('emrah_elvedin','Emrah','Zehić','M',6,'Grana Osman','','','elvedin_sevko','Elvedin','','',0);
INSERT INTO "clanovi" VALUES('amel_elvedin','Amel','Zehić','M',6,'Grana Osman','','','elvedin_sevko','Elvedin','','',0);
INSERT INTO "clanovi" VALUES('emina_elvedin','Emina','Zehić','Ž',6,'Grana Osman','','','elvedin_sevko','Elvedin','','',0);
INSERT INTO "clanovi" VALUES('adina_elvedin','Adina','Zehić','Ž',6,'Grana Osman','','','elvedin_sevko','Elvedin','','',0);
INSERT INTO "clanovi" VALUES('sefika_sahbaz','Šefika','Zehić','Ž',4,'Grana Osman','','','sahbaz_osman','Šahbaz','','',0);
INSERT INTO "clanovi" VALUES('mina_sahbaz','Mina','Zehić','Ž',4,'Grana Osman','','','sahbaz_osman','Šahbaz','','',0);
INSERT INTO "clanovi" VALUES('sp_ohro_sahbaz','Nizama','','Ž',4,'Grana Osman','','Supruga','ohro_sahbaz','Ohro','Ohro','',1);
INSERT INTO "clanovi" VALUES('ohro_sahbaz','Ohro','Zehić','M',4,'Grana Osman','','','sahbaz_osman','Šahbaz','Nizama','Supruga',0);
INSERT INTO "clanovi" VALUES('dzevad_ohro','Dževad','Zehić','M',5,'Grana Osman','','','ohro_sahbaz','Ohro','','',0);
INSERT INTO "clanovi" VALUES('elma_dzevad_o','Elma','Zehić','Ž',6,'Grana Osman','','','dzevad_ohro','Dževad','','',0);
INSERT INTO "clanovi" VALUES('mirsad_dzevad_o','Mirsad','Zehić','M',6,'Grana Osman','','','dzevad_ohro','Dževad','','',0);
INSERT INTO "clanovi" VALUES('nedzad_ohro','Nedžad','Zehić','M',5,'Grana Osman','','','ohro_sahbaz','Ohro','','',0);
INSERT INTO "clanovi" VALUES('tarik_nedzad_o','Tarik','Zehić','M',6,'Grana Osman','','','nedzad_ohro','Nedžad','','',0);
INSERT INTO "clanovi" VALUES('arnis_nedzad_o','Arnis','Zehić','M',6,'Grana Osman','','','nedzad_ohro','Nedžad','','',0);
INSERT INTO "clanovi" VALUES('idriz_arnis','Idriz','Zehić','M',7,'Grana Osman','','','arnis_nedzad_o','Arnis','','',0);
INSERT INTO "clanovi" VALUES('armin_nedzad_o','Armin','Zehić','M',6,'Grana Osman','','','nedzad_ohro','Nedžad','','',0);
INSERT INTO "clanovi" VALUES('zejn_armin_o','Zejn','Zehić','M',7,'Grana Osman','','','armin_nedzad_o','Armin','','',0);
INSERT INTO "clanovi" VALUES('hamza_armin_o','Hamza','Zehić','M',7,'Grana Osman','','','armin_nedzad_o','Armin','','',0);
INSERT INTO "clanovi" VALUES('zekerijah_armin_o','Zekerijah','Zehić','M',7,'Grana Osman','','','armin_nedzad_o','Armin','','',0);
INSERT INTO "clanovi" VALUES('amela_ohro_sahbaz','Amela','Zehić','Ž',5,'Grana Osman','','','ohro_sahbaz','Ohro','','',0);
INSERT INTO "clanovi" VALUES('nerka_ohro_sahbaz','Nerka','Zehić','Ž',5,'Grana Osman','','','ohro_sahbaz','Ohro','','',0);
INSERT INTO "clanovi" VALUES('emka_ohro_sahbaz','Emka','Zehić','Ž',5,'Grana Osman','','','ohro_sahbaz','Ohro','','',0);
INSERT INTO "clanovi" VALUES('sp_sacir_osman','Alta','','Ž',3,'Grana Osman','','Supruga','sacir_osman','Šaćir','Šaćir','',1);
INSERT INTO "clanovi" VALUES('sacir_osman','Šaćir','Zehić','M',3,'Grana Osman','1914 – 1999','','osman_1','Osman','Alta','Supruga',0);
INSERT INTO "clanovi" VALUES('mevla_sacir','Mevla','Zehić','Ž',4,'Grana Osman','','u. Mujagić (Centar)','sacir_osman','Šaćir','','',0);
INSERT INTO "clanovi" VALUES('seida_sacir','Seida','Zehić','Ž',4,'Grana Osman','','u. Omerović (Šepak)','sacir_osman','Šaćir','','',0);
INSERT INTO "clanovi" VALUES('sp_avdo_sacir','Izeta','','Ž',4,'Grana Osman','','r. Avdić','avdo_sacir','Avdo','Avdo','',1);
INSERT INTO "clanovi" VALUES('avdo_sacir','Avdo','Zehić','M',4,'Grana Osman','','','sacir_osman','Šaćir','Izeta','r. Avdić',0);
INSERT INTO "clanovi" VALUES('sp_izudin_avdo_sacir','Maksida','','Ž',5,'Grana Osman','','r. Krezić','izudin_avdo_sacir','Izudin','Izudin','',1);
INSERT INTO "clanovi" VALUES('izudin_avdo_sacir','Izudin','Zehić','M',5,'Grana Osman','','','avdo_sacir','Avdo','Maksida','r. Krezić',0);
INSERT INTO "clanovi" VALUES('alma_izudin','Alma','Zehić','Ž',6,'Grana Osman','','u. Muslić (Brnjik)','izudin_avdo_sacir','Izudin','','',0);
INSERT INTO "clanovi" VALUES('adin_alma','Adin','Zehić','M',7,'Grana Osman','','','alma_izudin','Alma','','',0);
INSERT INTO "clanovi" VALUES('amra_izudin','Amra','Zehić','Ž',6,'Grana Osman','','u. Čajlaković (Mumbašići)','izudin_avdo_sacir','Izudin','','',0);
INSERT INTO "clanovi" VALUES('faris_amra','Faris','Zehić','M',7,'Grana Osman','','','amra_izudin','Amra','','',0);
INSERT INTO "clanovi" VALUES('sp_mevludin_avdo_sacir','Remzija','','Ž',5,'Grana Osman','','r. Šabačkić','mevludin_avdo_sacir','Mevludin','Mevludin','',1);
INSERT INTO "clanovi" VALUES('mevludin_avdo_sacir','Mevludin','Zehić','M',5,'Grana Osman','','','avdo_sacir','Avdo','Remzija','r. Šabačkić',0);
INSERT INTO "clanovi" VALUES('samra_mevludin','Samra','Zehić','Ž',6,'Grana Osman','','u. Smajić (Bijeljina)','mevludin_avdo_sacir','Mevludin','','',0);
INSERT INTO "clanovi" VALUES('ajla_samra','Ajla','Zehić','Ž',7,'Grana Osman','','','samra_mevludin','Samra','','',0);
INSERT INTO "clanovi" VALUES('dzenan_samra','Dženan','Zehić','M',7,'Grana Osman','','','samra_mevludin','Samra','','',0);
INSERT INTO "clanovi" VALUES('sp_asmir_mevludin','Admira','','Ž',6,'Grana Osman','','r. Nukić','asmir_mevludin','Asmir','Asmir','',1);
INSERT INTO "clanovi" VALUES('asmir_mevludin','Asmir','Zehić','M',6,'Grana Osman','','','mevludin_avdo_sacir','Mevludin','Admira','r. Nukić',0);
INSERT INTO "clanovi" VALUES('lejla_asmir_m','Lejla','Zehić','Ž',7,'Grana Osman','','','asmir_mevludin','Asmir','','',0);
INSERT INTO "clanovi" VALUES('azijada_sacir','Azijada','Zehić','Ž',4,'Grana Osman','','u. Hamidović (Atmačići)','sacir_osman','Šaćir','','',0);
INSERT INTO "clanovi" VALUES('sp_omer_sacir','Fatima','','Ž',4,'Grana Osman','','r. Bilalić','omer_sacir','Omer','Omer','n. Poginuo 1995',1);
INSERT INTO "clanovi" VALUES('omer_sacir','Omer','Zehić','M',4,'Grana Osman','1995','n. Poginuo 1995','sacir_osman','Šaćir','Fatima','r. Bilalić',0);
INSERT INTO "clanovi" VALUES('zekira_omer_sacir','Zekira','Zehić','Ž',5,'Grana Osman','','u. Karasuljić (Čelić)','omer_sacir','Omer','','',0);
INSERT INTO "clanovi" VALUES('aldin_zekira','Aldin','Zehić','M',6,'Grana Osman','','','zekira_omer_sacir','Zekira','','',0);
INSERT INTO "clanovi" VALUES('naida_zekira','Naida','Zehić','Ž',6,'Grana Osman','','','zekira_omer_sacir','Zekira','','',0);
INSERT INTO "clanovi" VALUES('zehrina_omer_sacir','Zehrina','Zehić','Ž',5,'Grana Osman','','u. Jatić (Kozluk)','omer_sacir','Omer','','',0);
INSERT INTO "clanovi" VALUES('emina_zehrina','Emina','Zehić','Ž',6,'Grana Osman','','','zehrina_omer_sacir','Zehrina','','',0);
INSERT INTO "clanovi" VALUES('edina_zehrina','Edina','Zehić','Ž',6,'Grana Osman','','','zehrina_omer_sacir','Zehrina','','',0);
INSERT INTO "clanovi" VALUES('nermina_omer_sacir','Nermina','Zehić','Ž',5,'Grana Osman','','u. Hrustanović (Glinje)','omer_sacir','Omer','','',0);
INSERT INTO "clanovi" VALUES('almin_nermina','Almin','Zehić','M',6,'Grana Osman','','','nermina_omer_sacir','Nermina','','',0);
INSERT INTO "clanovi" VALUES('kenan_nermina','Kenan','Zehić','M',6,'Grana Osman','','','nermina_omer_sacir','Nermina','','',0);
INSERT INTO "clanovi" VALUES('neyla_nermina','Neyla','Zehić','Ž',6,'Grana Osman','','','nermina_omer_sacir','Nermina','','',0);
INSERT INTO "clanovi" VALUES('sp_nermin_omer_sacir','Ševala','','Ž',5,'Grana Osman','','r. Kadrić (Stari Teočak)','nermin_omer_sacir','Nermin','Nermin','',1);
INSERT INTO "clanovi" VALUES('nermin_omer_sacir','Nermin','Zehić','M',5,'Grana Osman','','','omer_sacir','Omer','Ševala','r. Kadrić (Stari Teočak)',0);
INSERT INTO "clanovi" VALUES('ajlin_nermin_os','Aylin','Zehić','Ž',6,'Grana Osman','','','nermin_omer_sacir','Nermin','','',0);
INSERT INTO "clanovi" VALUES('davud_nermin_os','Dawud','Zehić','M',6,'Grana Osman','','','nermin_omer_sacir','Nermin','','',0);
INSERT INTO "clanovi" VALUES('sp_muharem_osman','Mejra','','Ž',3,'Grana Osman','','Supruga','muharem_osman','Muharem','Muharem','',1);
INSERT INTO "clanovi" VALUES('muharem_osman','Muharem','Zehić','M',3,'Grana Osman','','','osman_1','Osman','Mejra','Supruga',0);
INSERT INTO "clanovi" VALUES('sp_resid_muharem','Aiša','','Ž',4,'Grana Osman','','Supruga','resid_muharem','Rešid','Rešid','',1);
INSERT INTO "clanovi" VALUES('resid_muharem','Rešid','Zehić','M',4,'Grana Osman','','','muharem_osman','Muharem','Aiša','Supruga',0);
INSERT INTO "clanovi" VALUES('zikreta_resid','Zikreta','Zehić','Ž',5,'Grana Osman','','','resid_muharem','Rešid','','',0);
INSERT INTO "clanovi" VALUES('zekerijah_resid','Zekerijah','Zehić','M',5,'Grana Osman','','','resid_muharem','Rešid','','',0);
INSERT INTO "clanovi" VALUES('mensur_resid','Mensur','Zehić','M',5,'Grana Osman','','','resid_muharem','Rešid','','',0);
INSERT INTO "clanovi" VALUES('sp_rasim_muharem','Kadira','','Ž',4,'Grana Osman','','Supruga','rasim_muharem','Rasim','Rasim','',1);
INSERT INTO "clanovi" VALUES('rasim_muharem','Rasim','Zehić','M',4,'Grana Osman','','','muharem_osman','Muharem','Kadira','Supruga',0);
INSERT INTO "clanovi" VALUES('ramiz_rasim','Ramiz','Zehić','M',5,'Grana Osman','','','rasim_muharem','Rasim','','',0);
INSERT INTO "clanovi" VALUES('selma_ramiz_poginula','Selma','Zehić','Ž',6,'Grana Osman','','n. Poginula','ramiz_rasim','Ramiz','','',0);
INSERT INTO "clanovi" VALUES('almir_ramiz','Almir','Zehić','M',6,'Grana Osman','','','ramiz_rasim','Ramiz','','',0);
INSERT INTO "clanovi" VALUES('amra_almir_r','Amra','Zehić','Ž',7,'Grana Osman','','','almir_ramiz','Almir','','',0);
INSERT INTO "clanovi" VALUES('adna_almir_r','Adna','Zehić','Ž',7,'Grana Osman','','','almir_ramiz','Almir','','',0);
INSERT INTO "clanovi" VALUES('hanifa_rasim','Hanifa','Zehić','Ž',5,'Grana Osman','','','rasim_muharem','Rasim','','',0);
INSERT INTO "clanovi" VALUES('dzemila_rasim','Džemila','Zehić','Ž',5,'Grana Osman','','','rasim_muharem','Rasim','','',0);
INSERT INTO "clanovi" VALUES('rizvo_rasim','Rizvo','Zehić','M',5,'Grana Osman','','','rasim_muharem','Rasim','','',0);
INSERT INTO "clanovi" VALUES('sanela_rizvo','Sanela','Zehić','Ž',6,'Grana Osman','','','rizvo_rasim','Rizvo','','',0);
INSERT INTO "clanovi" VALUES('admira_rizvo','Admira','Zehić','Ž',6,'Grana Osman','','','rizvo_rasim','Rizvo','','',0);
INSERT INTO "clanovi" VALUES('admir_rizvo','Admir','Zehić','M',6,'Grana Osman','','','rizvo_rasim','Rizvo','','',0);
INSERT INTO "clanovi" VALUES('armina_admir_r','Armina','Zehić','Ž',7,'Grana Osman','','','admir_rizvo','Admir','','',0);
INSERT INTO "clanovi" VALUES('amina_admir_r','Amina','Zehić','Ž',7,'Grana Osman','','','admir_rizvo','Admir','','',0);
INSERT INTO "clanovi" VALUES('irfan_rasim','Irfan','Zehić','M',5,'Grana Osman','','','rasim_muharem','Rasim','','',0);
INSERT INTO "clanovi" VALUES('sabina_irfan','Sabina','Zehić','Ž',6,'Grana Osman','','','irfan_rasim','Irfan','','',0);
INSERT INTO "clanovi" VALUES('jasmina_irfan','Jasmina','Zehić','Ž',6,'Grana Osman','','','irfan_rasim','Irfan','','',0);
INSERT INTO "clanovi" VALUES('jasmin_irfan','Jasmin','Zehić','M',6,'Grana Osman','','','irfan_rasim','Irfan','','',0);
INSERT INTO "clanovi" VALUES('konstantin_jasmin_i','Konstantin','Zehić','M',7,'Grana Osman','','','jasmin_irfan','Jasmin','','',0);
INSERT INTO "clanovi" VALUES('viktor_jasmin_i','Viktor','Zehić','M',7,'Grana Osman','','','jasmin_irfan','Jasmin','','',0);
INSERT INTO "clanovi" VALUES('hanka_muharem','Hanka','Zehić','Ž',4,'Grana Osman','','','muharem_osman','Muharem','','',0);
INSERT INTO "clanovi" VALUES('malka_muharem','Malka','Zehić','Ž',4,'Grana Osman','','','muharem_osman','Muharem','','',0);
INSERT INTO "clanovi" VALUES('tifa_muharem','Tifa','Zehić','Ž',4,'Grana Osman','','','muharem_osman','Muharem','','',0);
INSERT INTO "clanovi" VALUES('sp_mehmedalija_muharem','Rajfa','','Ž',4,'Grana Osman','','Supruga','mehmedalija_muharem','Mehmedalija','Mehmedalija','',1);
INSERT INTO "clanovi" VALUES('mehmedalija_muharem','Mehmedalija','Zehić','M',4,'Grana Osman','','','muharem_osman','Muharem','Rajfa','Supruga',0);
INSERT INTO "clanovi" VALUES('seudin_mehmedalija','Seudin','Zehić','M',5,'Grana Osman','','','mehmedalija_muharem','Mehmedalija','','',0);
INSERT INTO "clanovi" VALUES('suvad_seudin','Suvad','Zehić','M',6,'Grana Osman','','','seudin_mehmedalija','Seudin','','',0);
INSERT INTO "clanovi" VALUES('sara_suvad','Sara','Zehić','Ž',7,'Grana Osman','','','suvad_seudin','Suvad','','',0);
INSERT INTO "clanovi" VALUES('malik_suvad','Malik','Zehić','M',7,'Grana Osman','','','suvad_seudin','Suvad','','',0);
INSERT INTO "clanovi" VALUES('dzevida_seudin','Dževida','Zehić','Ž',6,'Grana Osman','','','seudin_mehmedalija','Seudin','','',0);
INSERT INTO "clanovi" VALUES('dzevad_seudin','Dževad','Zehić','M',6,'Grana Osman','','','seudin_mehmedalija','Seudin','','',0);
INSERT INTO "clanovi" VALUES('eldin_dzevad_s','Eldin','Zehić','M',7,'Grana Osman','','','dzevad_seudin','Dževad','','',0);
INSERT INTO "clanovi" VALUES('anel_dzevad_s','Anel','Zehić','M',7,'Grana Osman','','','dzevad_seudin','Dževad','','',0);
INSERT INTO "clanovi" VALUES('elma_dzevad_s','Elma','Zehić','Ž',7,'Grana Osman','','','dzevad_seudin','Dževad','','',0);
INSERT INTO "clanovi" VALUES('remza_mehmedalija','Remza','Zehić','Ž',5,'Grana Osman','','','mehmedalija_muharem','Mehmedalija','','',0);
INSERT INTO "clanovi" VALUES('jusuf_mehmedalija','Jusuf','Zehić','M',5,'Grana Osman','','','mehmedalija_muharem','Mehmedalija','','',0);
INSERT INTO "clanovi" VALUES('emina_jusuf','Emina','Zehić','Ž',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('mehmedalija_jusuf','Mehmedalija','Zehić','M',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('amir_jusuf','Amir','Zehić','M',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('amra_jusuf','Amra','Zehić','Ž',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('almedina_jusuf','Almedina','Zehić','Ž',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('senad_jusuf','Senad','Zehić','M',6,'Grana Osman','','','jusuf_mehmedalija','Jusuf','','',0);
INSERT INTO "clanovi" VALUES('nasiha_mehmedalija','Nasiha','Zehić','Ž',5,'Grana Osman','','','mehmedalija_muharem','Mehmedalija','','',0);
INSERT INTO "clanovi" VALUES('sefik_mehmedalija','Šefik','Zehić','M',5,'Grana Osman','','','mehmedalija_muharem','Mehmedalija','','',0);
INSERT INTO "clanovi" VALUES('edina_sefik_m','Edina','Zehić','Ž',6,'Grana Osman','','','sefik_mehmedalija','Šefik','','',0);
INSERT INTO "clanovi" VALUES('sp_edin_sefik_m','Mubina','','Ž',6,'Grana Osman','','Supruga','edin_sefik_m','Edin','Edin','',1);
INSERT INTO "clanovi" VALUES('edin_sefik_m','Edin','Zehić','M',6,'Grana Osman','','','sefik_mehmedalija','Šefik','Mubina','Supruga',0);
INSERT INTO "clanovi" VALUES('dzenana_edin_s','Dženana','Zehić','Ž',7,'Grana Osman','','','edin_sefik_m','Edin','','',0);
INSERT INTO "clanovi" VALUES('mirsad_edin_s','Mirsad','Zehić','M',7,'Grana Osman','','','edin_sefik_m','Edin','','',0);
INSERT INTO "clanovi" VALUES('elmir_edin_s','Elmir','Zehić','M',7,'Grana Osman','','','edin_sefik_m','Edin','','',0);
INSERT INTO "clanovi" VALUES('elma_edin_s','Elma','Zehić','Ž',7,'Grana Osman','','','edin_sefik_m','Edin','','',0);
INSERT INTO "clanovi" VALUES('adis_edin_s','Adis','Zehić','M',7,'Grana Osman','','','edin_sefik_m','Edin','','',0);
INSERT INTO "clanovi" VALUES('maja_adis','Maja','Zehić','Ž',8,'Grana Osman','','','adis_edin_s','Adis','','',0);
INSERT INTO "clanovi" VALUES('nurif_1','Nurif','Zehić','M',2,'Grana Nurif','r. 1863','nije se ženio','ibrahim_root','Ibrahim','','',0);
INSERT INTO "clanovi" VALUES('pasa_1','Paša','Zehić','Ž',2,'Grana Paša','','udata u Glinje u porodicu Hrustanović','ibrahim_root','Ibrahim','','',0);
CREATE INDEX idx_ime ON clanovi(ime);
CREATE INDEX idx_grana ON clanovi(grana);
CREATE INDEX idx_generacija ON clanovi(generacija);
CREATE INDEX idx_spol ON clanovi(spol);
COMMIT;
